version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing source NPM dependencies..."
      - npm install
  build:
    commands:
      - echo "Build started on `date`"
      - node ./node_modules/serverless/bin/serverless.js deploy -s dev --verbose
  post_build:
    commands:
      - echo "Build completed on `date`"
